name: Checkout Workflow
on: workflow_dispatch
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
        with:
          repository: actions/checkout
          ref: v3
      - run: cat CHANGELOG.md
