name: GitHub Actions Variable Test

on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  test-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print Repository Variable
        run: |
          echo "The value of JOB_NAME is: ${{ vars.JOB_NAME }}"

      - name: Example Usage of JOB_NAME
        run: |
          if [[ "${{ vars.JOB_NAME }}" == "var-test" ]]; then
            echo "JOB_NAME matches 'var-test'. Test passed!"
          else
            echo "JOB_NAME does not match 'var-test'. Test failed."
            exit 1
          fi
